library("RPostgreSQL")
library("ggplot2")
library("tidyverse")
library("ggridges")
library("hrbrthemes")
library("stringr")
library("scales")
library("DescTools")
library("zoo")
library("ggpubr")
library("lubridate")
library("viridis")

source('inc/database.R')
source('inc/prepare_data.R')
source('inc/transformation.R')